### ISSUE TITLE
Subdomain service does not work in Kubernetes 1.11

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon-deploy#63]
Should add the following to `browsers` service:
```
ports:
   - name: moon
     port: 4444
     protocol: TCP
     targetPort: 4444
   - name: moon2
     port: 5900
     protocol: TCP
     targetPort: 5900
```
