### ISSUE TITLE
Added liveness and readiness probe

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/moon-deploy#66]
```
      spec:
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5

```
