### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Asgoret** [aerokube/moon-deploy#71]
Hi!
How to configure which service account to use? By default, the moon tries to use SA "default" which already exist in namespace and belong to system SA. If I created another SA moon doesn't us it.

Issue:
```
2020/04/14 13:36:59 [INIT] [Failed to initialize license: failed to load initial pods limit: failed to fetch required resource quota information: resourcequotas is forbidden: User "system:serviceaccount:moon:default" cannot list resourcequotas in the namespace "moon": no RBAC policy matched]
```

**Comment by vania-pooh** [comment]
Related to https://github.com/aerokube/moon/issues/128.

**Comment by Asgoret** [comment]
@vania-pooh and when it will be done?) Year has gone since you opened that issue :)

**Comment by vania-pooh** [comment]
@Asgoret added docs about it here: https://aerokube.com/moon/latest/#_using_custom_service_account

**Comment by Asgoret** [comment]
@vania-pooh Thanks! I will try this and open error issue if something goes wrong :)

**Comment by Asgoret** [comment]
@vania-pooh one quesiont...for what does moon need node port?

**Comment by vania-pooh** [comment]
@Asgoret this was fixed in Moon 1.4.2. Starting from this release it does not add `SYS_ADMIN` capability.

**Comment by Asgoret** [comment]
@vania-pooh And another (in OKD 3.11 if it's necessary :)
```
2020/04/21 07:28:24 [FORBIDDEN_TO_CREATE_POD] [browsers] [<POD IP 1>, <POD IP 2>] [chrome-48-0-9624ff5b-923d-4b66-ac6a-5b00eb1c9033] [pods "chrome-48-0-9624ff5b-923d-4b66-ac6a-5b00eb1c9033" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{65534}: 65534 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 106: must be in the ranges: [1000330000, 1000339999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 106: must be in the ranges: [1000330000, 1000339999]]] [0.03s]
```

**Comment by Asgoret** [comment]
@vania-pooh I think that I found all security issues, so some update for documentation (or template for openshift as you decide):
1. Namespace role for service:
```
  - kind: Role
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      labels:
        app: moon
      name: moon-role
      annotations:
        rbac.authorization.kubernetes.io/autoupdate: 'false'
    rules:
      - verbs:
          - create
          - delete
          - get
          - list
          - watch
        apiGroups:
          - ''
        resources:
          - pods
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - ''
        resources:
          - configmaps
          - resourcequotas
          - secrets  
          - services
          - persistentvolumeclaims
```

And 1 question: why pod with browser mount secret of default SA? It must mount token for his define SA
